version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///data/bar_cocktails.db
      - SECRET_KEY=your-secret-key-here