version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile  # ← Pointer vers Dockerfile avec majuscule
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance  # Synchronise le dossier instance entre l'hôte et le conteneur
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/instance/bar_cocktails.db
      - OLLAMA_URL=http://ollama:11434
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - ollama
    networks:
      - cocktail-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - cocktail-network
    # Commande pour télécharger le modèle au démarrage
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & 
       sleep 10 && 
       ollama pull llama3.2 && 
       wait"

volumes:
  ollama-data:

networks:
  cocktail-network:
    driver: bridge