version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance  # ← Changé de 'data' vers 'instance'
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///instance/bar_cocktails.db
      - SECRET_KEY=your-secret-key-here